version: "3"
services:
  caddy:
    build: 
      context: '.'
    ports:
      - '${CADDY_HOST_HTTP_PORT}:80'
    volumes:
      - '${APP_CODE_PATH_HOST}/data:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}'
      - '${APP_CODE_PATH_HOST}/srv:/srv'  
    expose:
      - '9000'
volumes: {}
