name: redis

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
      